name: demo_application
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.3
  get_it: ^7.7.0
  logger: ^2.4.0
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.2.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.5
  dartz: ^0.10.1  #function programming
  provider: ^6.1.2
  geolocator: ^13.0.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  dart_sentiment: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  retrofit_generator: ^8.2.0
  json_serializable: ^6.8.0
  freezed: ^2.5.7

#dependency_overrides:
#  analyzer:


flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/


  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 200