import 'package:flutter/material.dart';

import 'font_family.dart';

final textTheme = const TextTheme().copyWith(
  displayLarge: const TextStyle(
    debugLabel: 'englishLike displayLarge 2021',
    inherit: true,
    fontSize: 57,
    fontWeight: FontWeight.w400,
    letterSpacing: -0.25,
    height: 1.12,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  displayMedium: const TextStyle(
    debugLabel: 'englishLike displayMedium 2021',
    inherit: true,
    fontSize: 45,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.16,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  displaySmall: const TextStyle(
    debugLabel: 'englishLike displaySmall 2021',
    inherit: true,
    fontSize: 36,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.22,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  headlineLarge: const TextStyle(
    debugLabel: 'englishLike headlineLarge 2021',
    inherit: true,
    fontSize: 32,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.25,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  headlineMedium: const TextStyle(
    debugLabel: 'englishLike headlineMedium 2021',
    inherit: true,
    fontSize: 28,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.29,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  headlineSmall: const TextStyle(
    debugLabel: 'englishLike headlineSmall 2021',
    inherit: true,
    fontSize: 24,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  titleLarge: const TextStyle(
    debugLabel: 'englishLike titleLarge 2021',
    inherit: true,
    fontSize: 22,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.27,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  titleMedium: const TextStyle(
    debugLabel: 'englishLike titleMedium 2021',
    inherit: true,
    fontSize: 16,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.50,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  titleSmall: const TextStyle(
    debugLabel: 'englishLike titleSmall 2021',
    inherit: true,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  labelLarge: const TextStyle(
    debugLabel: 'englishLike labelLarge 2021',
    inherit: true,
    fontSize: 14,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  labelMedium: const TextStyle(
    debugLabel: 'englishLike labelMedium 2021',
    inherit: true,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  labelSmall: const TextStyle(
    debugLabel: 'englishLike labelSmall 2021',
    inherit: true,
    fontSize: 12,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.45,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  bodyLarge: const TextStyle(
    debugLabel: 'englishLike bodyLarge 2021',
    inherit: true,
    fontSize: 16,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
    height: 1.50,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  bodyMedium: const TextStyle(
    debugLabel: 'englishLike bodyMedium 2021',
    inherit: true,
    fontSize: 14,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
  bodySmall: const TextStyle(
    debugLabel: 'englishLike bodySmall 2021',
    inherit: true,
    fontSize: 12,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
    fontFamily: FontFamily.sfProfFont,
  ),
);
